spring.application.name=pc_health_server

spring.datasource.url=jdbc:postgresql://localhost:5432/pc_health_check
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.yml

#logging.level.liquibase=DEBUG


# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000/realms/development
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8000/realms/development/protocol/openid-connect/certs

# Spring Security Logging
logging.level.org.springframework.security=DEBUG

# Custom JWT Converter Properties
jwt.auth.converter.resource-id=springboot-client
jwt.auth.converter.principle-attribute=preferred_username
