services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command:
      - start-dev
      - --import-realm

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      

    ports:
      - "8000:8080"

    volumes:
      - ../../keycloak/realms/:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data: